# Generated by Django 5.0 on 2024-01-21 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_alter_userprofile_address_alter_userprofile_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(default='XXXXXXXXXX', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='No name', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(default='XXXXXX', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(default='No surname', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
