# Generated by Django 5.0 on 2024-01-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_alter_userprofile_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
