# Generated by Django 5.0 on 2024-01-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0014_rename_name_paymentgate_namee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentGate',
        ),
    ]
