# Generated by Django 5.0 on 2024-01-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0017_alter_contribution_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='captcha_score',
            field=models.FloatField(default=0.0),
        ),
    ]
