# Generated by Django 5.0 on 2024-01-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0019_verify_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verify_contribution',
            name='Verify_latitude',
        ),
        migrations.RemoveField(
            model_name='verify_contribution',
            name='Verify_longitude',
        ),
    ]
