# Generated by Django 5.0 on 2024-01-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('points', models.IntegerField()),
                ('is_redeemed', models.BooleanField(default=False)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('last_redeemed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
