# Generated by Django 5.0 on 2024-02-10 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='redeemCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('desc', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScratchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('points', models.IntegerField()),
                ('is_redeemed', models.BooleanField(default=False)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('last_redeemed_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
