# Generated by Django 5.0 on 2024-01-17 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratchcard',
            name='cid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
