# Generated by Django 5.0 on 2024-02-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_redeemcards_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_pts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalpts', models.IntegerField(default=0)),
            ],
        ),
    ]
