# Generated by Django 5.0 on 2024-02-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_total_pts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemcards',
            name='user',
        ),
    ]
