// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA12cnafFpivgynlWD-uP0-KZv57o-Fo1c',
    appId: '1:813071655858:web:dc4d79d4c24a2041847aab',
    messagingSenderId: '813071655858',
    projectId: 'solution-challenge-app-409f6',
    authDomain: 'solution-challenge-app-409f6.firebaseapp.com',
    storageBucket: 'solution-challenge-app-409f6.appspot.com',
    measurementId: 'G-CN4J906YXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBELbEZ9eE6FFqDj4Rt2wtBhoEesKc6J-w',
    appId: '1:813071655858:android:0446c35999bc2035847aab',
    messagingSenderId: '813071655858',
    projectId: 'solution-challenge-app-409f6',
    storageBucket: 'solution-challenge-app-409f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_88R7b_6WP-zO54Z73GbD5RtDUkdsvR4',
    appId: '1:813071655858:ios:2651682a52438e5d847aab',
    messagingSenderId: '813071655858',
    projectId: 'solution-challenge-app-409f6',
    storageBucket: 'solution-challenge-app-409f6.appspot.com',
    iosBundleId: 'com.example.solutionChallengeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_88R7b_6WP-zO54Z73GbD5RtDUkdsvR4',
    appId: '1:813071655858:ios:18cbf351408f7727847aab',
    messagingSenderId: '813071655858',
    projectId: 'solution-challenge-app-409f6',
    storageBucket: 'solution-challenge-app-409f6.appspot.com',
    iosBundleId: 'com.example.solutionChallengeApp.RunnerTests',
  );
}
