# Generated by Django 5.0 on 2024-01-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=1, verbose_name=False),
            preserve_default=False,
        ),
    ]
