# Generated by Django 5.0 on 2024-01-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_user_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('education', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state_region', models.CharField(max_length=100)),
            ],
        ),
    ]
