# Generated by Django 5.0 on 2024-01-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='No Address Provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='area',
            field=models.CharField(default='Unknown Area', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Unknown Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(default='No Education Information', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state_region',
            field=models.CharField(default='Unknown Region', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(default='Doe', max_length=100),
        ),
    ]
