# Generated by Django 5.0 on 2024-01-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_paymentgate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentgate',
            old_name='name',
            new_name='namee',
        ),
    ]
