# Generated by Django 5.0 on 2024-01-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0016_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contributions/'),
        ),
    ]
