# Generated by Django 5.0 on 2024-01-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0018_userprofile_captcha_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify_Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Verify_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Verify_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Verify_image', models.ImageField(blank=True, null=True, upload_to='Verify_contributions/')),
            ],
        ),
    ]
