# Generated by Django 5.0 on 2024-01-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_authorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='authorProfile',
        ),
    ]
