# Generated by Django 5.0 on 2024-01-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0002_verificationresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationResult',
        ),
    ]
