# Generated by Django 5.0 on 2024-01-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_delete_verificationresult'),
        ('userauths', '0020_remove_verify_contribution_verify_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('prediction', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauths.contribution')),
            ],
        ),
    ]
