# Generated by Django 5.0 on 2024-01-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0004_verificationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('prediction', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='VerificationResult',
        ),
    ]
