# Generated by Django 5.0 on 2024-01-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0006_predictionmodel_score_of_image_predictionmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionmodel',
            name='score_of_image',
            field=models.IntegerField(default='0'),
        ),
    ]
