# Generated by Django 5.0 on 2024-01-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0007_alter_predictionmodel_score_of_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
